{"timestamp":"2025-06-12T16:25:11.352158","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-12T16:25:11.354058","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-12T16:25:11.430574Z","level":"error","event":"%3|1749745511.430|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 1ms in state CONNECT)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-12T16:25:11.477268Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:25:11.477478Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:25:11.477622Z","level":"info","event":"Current task name:load_connections","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:25:11.477752Z","level":"info","event":"Dag name:consume_kafka_msgs","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:25:11.477866Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:25:11.477968Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:25:11.478068Z","level":"info","event":"Task:<Task(PythonOperator): load_connections>","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:25:11.478164Z","level":"info","event":"Failure caused by Direct database access via the ORM is not allowed in Airflow 3.0","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:25:11.450715","level":"warning","event":"empty cryptography key - values will not be stored encrypted.","logger":"airflow.models.crypto"}
{"timestamp":"2025-06-12T16:25:11.451325","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"RuntimeError","exc_value":"Direct database access via the ORM is not allowed in Airflow 3.0","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":838,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1130,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/dag.py","lineno":35,"name":"load_connections"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py","lineno":100,"name":"wrapper"},{"filename":"/usr/local/lib/python3.12/contextlib.py","lineno":137,"name":"__enter__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py","lineno":41,"name":"create_session"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/supervisor.py","lineno":251,"name":"__init__"}]}]}
